import {
    ClassicEditor,
    Bold,
    Essentials,
    Italic,
    Mention,
    Paragraph,
    Undo,
    Font,
    ImageBlock,
    ImageCaption,
    ImageInline,
    ImageInsert,
    ImageInsertViaUrl,
    ImageResize,
    ImageStyle,
    ImageTextAlternative,
    ImageToolbar,
    ImageUpload,
    Link,
    Heading,
    List,
    Indent,
    Table,
    Alignment,
    MediaEmbed,
    Highlight,
    BlockQuote,
    Base64UploadAdapter,
    TableCaption,
    TableCellProperties,
    TableColumnResize,
    TableProperties,
    TableToolbar,
    HtmlComment,
    HtmlEmbed,
    ShowBlocks,
    CodeBlock
} from "ckeditor5";


const editor = ClassicEditor;

const editorConfig = {
    plugins: [
        Bold,
        Essentials,
        Italic,
        Mention,
        Paragraph,
        Undo,
        Font,
        ImageBlock,
        ImageCaption,
        ImageInline,
        ImageInsert,
        ImageInsertViaUrl,
        ImageResize,
        ImageStyle,
        ImageTextAlternative,
        ImageToolbar,
        ImageUpload,
        Link,
        Heading,
        List,
        Indent,
        Table,
        TableCaption,
        TableCellProperties,
        TableColumnResize,
        TableProperties,
        TableToolbar,
        Alignment,
        MediaEmbed,
        Highlight,
        BlockQuote,
        Base64UploadAdapter,
        HtmlComment,
        HtmlEmbed,
        ShowBlocks,
        CodeBlock
    ],
    toolbar: [
        "undo",
        "redo",
        "heading",
        "|",
        "fontSize",
        "fontFamily",
        "fontColor",
        "fontBackgroundColor",
        "|",
        "bold",
        "italic",
        "insertImage",
        "link",
        "bulletedList",
        "numberedList",
        "indent",
        "outdent",
        "insertTable",
        "alignment",
        "mediaEmbed",
        "highlight",
        "|",
        "blockQuote",
        "showBlocks",
        "codeBlock",
    ],
    image: {
        toolbar: [
            "toggleImageCaption",
            "imageTextAlternative",
            "|",
            "imageStyle:inline",
            "imageStyle:wrapText",
            "imageStyle:breakText",
            "|",
            "resizeImage",
        ],
    },
    fontSize: {
        options: [10, 12, 14, "default", 18, 20, 22, 26, 28, 32, 48],
        supportAllValues: true,
    },
    table: {
        contentToolbar: [
            "tableColumn",
            "tableRow",
            "mergeTableCells",
            "tableProperties",
            "tableCellProperties",
        ],
    },
    htmlSupport: {
        allow: [
            {
                name: /^.*$/,
                styles: true,
                attributes: true,
                classes: true,
            },
        ],
    },
};

export { ClassicEditor as editor, editorConfig };
